# Generated by Django 5.2.5 on 2026-06-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MENTOR', 'Mentor'), ('STUDENT', 'Mentee')], default='STUDENT', max_length=20),
        ),
    ]
