# Generated by Django 5.2.16 on 2026-07-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='user_cv/%Y/%m/'),
        ),
    ]
