# Generated by Django 6.0.7 on 2026-09-17 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('filter_type', models.CharField(choices=[('ALL', 'Semua User'), ('ROLE', 'Per Role'), ('BOUGHT_PRODUCT', 'Sudah Beli Produk Ini'), ('BOOTCAMP_REGISTERED', 'Sudah Daftar Bootcamp Ini'), ('MANUAL', 'Daftar Email Manual')], max_length=30)),
                ('filter_summary', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Email',
                'verbose_name_plural': 'Broadcast Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
