# Generated by Django 6.0.7 on 2026-09-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_broadcastemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastemail',
            name='filter_type',
            field=models.CharField(choices=[('ALL', 'Semua User'), ('ROLE', 'Per Role'), ('BOUGHT_PRODUCT', 'Sudah Beli Produk Ini'), ('BOOTCAMP_REGISTERED', 'Sudah Daftar Bootcamp Ini'), ('BOOTCAMP_UNPAID', 'Diterima Tapi Belum Bayar (Bootcamp)'), ('MANUAL', 'Daftar Email Manual')], max_length=30),
        ),
    ]
