# Generated by Django 6.0.7 on 2026-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_broadcastemail_filter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastemail',
            name='filter_type',
            field=models.CharField(choices=[('ALL', 'Semua User'), ('ROLE', 'Per Role'), ('BOUGHT_PRODUCT', 'Sudah Beli Produk Ini'), ('BOOTCAMP_REGISTERED', 'Bootcamp'), ('MANUAL', 'Daftar Email Manual')], max_length=30),
        ),
    ]
