# Generated by Django 5.2.5 on 2026-06-22 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0001_initial'),
        ('products', '0002_review'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Competition Category',
                'verbose_name_plural': 'Competition Categories',
                'db_table': 'competition_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BootcampSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='products.bootcampproduct')),
            ],
            options={
                'verbose_name': 'Bootcamp Session',
                'verbose_name_plural': 'Bootcamp Sessions',
                'db_table': 'bootcamp_sessions',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='BootcampSessionMentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bootcamp_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_mentors', to='programs.bootcampsession')),
                ('mentor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_session_assignments', to='mentors.mentorprofile')),
            ],
            options={
                'verbose_name': 'Bootcamp Session Mentor',
                'verbose_name_plural': 'Bootcamp Session Mentors',
                'db_table': 'bootcamp_session_mentors',
                'ordering': ['bootcamp_session', 'mentor_profile'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deadline', models.DateTimeField()),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='programs.competitioncategory')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'db_table': 'competitions',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='mentors.mentoravailability')),
                ('mentor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='mentors.mentorprofile')),
                ('transaction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='transactions.transactionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentoring Session',
                'verbose_name_plural': 'Mentoring Sessions',
                'db_table': 'mentoring_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bootcampsession',
            index=models.Index(fields=['start_time'], name='bootcamp_se_start_t_0daf61_idx'),
        ),
        migrations.AddConstraint(
            model_name='bootcampsessionmentor',
            constraint=models.UniqueConstraint(fields=('bootcamp_session', 'mentor_profile'), name='unique_bootcamp_session_mentor'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['deadline'], name='competition_deadlin_5d7ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoringsession',
            index=models.Index(fields=['status'], name='mentoring_s_status_356167_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoringsession',
            index=models.Index(fields=['user'], name='mentoring_s_user_id_f589c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mentoringsession',
            index=models.Index(fields=['mentor_profile'], name='mentoring_s_mentor__d9a6f7_idx'),
        ),
    ]
