# Generated by Django 5.2.16 on 2026-07-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_delete_mentoringsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='competition_posters/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='image_url',
            field=models.URLField(blank=True, help_text='Legacy -- link poster lama. Dipakai fallback kalau `image` (file upload) belum diisi.', null=True),
        ),
    ]
