# Generated by Django 5.2.16 on 2026-07-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_competition_image_alter_competition_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcampsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcampsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
