# Generated by Django 5.2.16 on 2026-07-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_bootcampsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootcampsession',
            options={'ordering': ['order', 'start_time'], 'verbose_name': 'Bootcamp Session', 'verbose_name_plural': 'Bootcamp Sessions'},
        ),
        migrations.AddField(
            model_name='bootcampsession',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
