# Generated by Django 5.2.16 on 2026-07-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_backfill_bootcamp_session_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampsession',
            name='required_benefit',
            field=models.CharField(blank=True, choices=[('mentoring_case', 'Mentoring Case Competition'), ('career_coaching', 'Career Coaching'), ('networking', 'Networking Session')], default='', max_length=30),
        ),
    ]
