# Generated by Django 5.2.16 on 2026-08-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_bootcampresource_packages_and_more'),
        ('programs', '0009_bootcampsession_required_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampsession',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='Paket mana yang dapat sesi ini. KOSONG = semua peserta bootcamp ini. Menggantikan required_benefit yang cuma bisa 3 kategori tetap dan gak bisa diatur admin dari panel.', related_name='session_templates', to='products.bootcamppackage'),
        ),
        migrations.AlterField(
            model_name='bootcampsession',
            name='required_benefit',
            field=models.CharField(blank=True, choices=[('mentoring_case', 'Mentoring Case Competition'), ('career_coaching', 'Career Coaching'), ('networking', 'Networking Session')], default='', help_text='USANG -- diganti field `packages`. Masih disimpan buat jejak data lama.', max_length=30),
        ),
    ]
