# Generated by Django 5.2.16 on 2026-08-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_bootcampresource_for_all_packages_and_more'),
        ('programs', '0010_bootcampsession_packages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampsession',
            name='for_all_packages',
            field=models.BooleanField(default=True, help_text='True = semua peserta bootcamp ini dapat sesi ini. False = cuma paket yang dipilih di `packages`.'),
        ),
        migrations.AlterField(
            model_name='bootcampsession',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='Dipakai cuma kalau for_all_packages=False. Menggantikan required_benefit yang cuma bisa 3 kategori tetap & gak bisa diatur admin dari panel.', related_name='session_templates', to='products.bootcamppackage'),
        ),
    ]
