"""
Django settings for mark_up project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# Load environment variables from .env file
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

PRODUCTION = os.getenv("PRODUCTION", "False").lower() == "true"

# Default ke False (aman) kalau env var DEBUG lupa di-set -- server produksi
# yang ke-deploy tanpa .env lengkap gak akan diam-diam kebuka stack trace +
# query SQL ke publik. Dev lokal tetap jalan normal karena .env di sini
# eksplisit set DEBUG=True.
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

# Hardening HTTPS/cookie -- cuma aktif kalau PRODUCTION=true di .env, jadi
# gak ganggu dev lokal (http://localhost) yang emang belum pakai TLS.
if PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 hari
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "storages",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "accounts",
    "mentors",
    "products",
    "transactions",
    "programs",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mark_up.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'mark_up.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mark_up.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Cache -- dipakai rate limiter (is_rate_limited) buat throttle brute-force &
# spam. WAJIB backend yang SHARED antar-proses di produksi: Gunicorn jalan
# multi-worker, kalau pakai LocMemCache (default) tiap worker punya penghitung
# sendiri -> limit efektif jadi berkali lipat lebih longgar (gampang di-bypass).
# DatabaseCache pakai PostgreSQL yang udah ada, konsisten lintas worker, dan
# tahan restart. Tabelnya dibuat sekali lewat `manage.py createcachetable`.
if os.getenv("PRODUCTION", "False").lower() == "true":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "markup_cache",
        }
    }


# Logging -- sebelumnya nggak dikonfigurasi sama sekali, jadi error internal
# cuma nyangkut di stderr Gunicorn lewat handler darurat bawaan Python.
# Sekarang view yang nangkep Exception (mis. checkout) bisa nulis traceback
# lengkap ke log server, sementara respons ke user tetap pesan umum yang
# nggak bocorin struktur DB/storage.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        # stderr -- ditangkap systemd/Gunicorn (--error-logfile -), jadi
        # kebaca lewat `journalctl -u gunicorn`.
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'accounts.validators.SimplePasswordValidator',
    },
    {
        # Nolak password yang ada di daftar 20.000 password paling sering
        # dipakai/bocor. "Password1!" lolos aturan panjang+kapital+simbol tapi
        # ditebak duluan sama penyerang. Validator bawaan Django yang lain
        # (similarity/numeric) sengaja TIDAK dipakai -- sesuai keputusan
        # sebelumnya yang menilai itu terlalu ribet buat user.
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    os.getenv("FRONTEND_URL"),
    os.getenv("FRONTEND_URL_ALT"),
]

CSRF_TRUSTED_ORIGINS = [
    os.getenv("FRONTEND_URL"),
    os.getenv("FRONTEND_URL_ALT"),
]

CORS_ALLOW_CREDENTIALS = True

# Email
# Belum ada SMTP beneran -- default ke console backend (email ke-print di
# log server) biar alur lupa password tetap bisa dites di dev. Isi
# EMAIL_HOST dkk di .env begitu ada kredensial SMTP asli buat production.
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "")

# Urutan pilihan backend email:
#   1. API Brevo lewat HTTPS -- provider hosting ini MEMBLOKIR SMTP keluar
#      (DNS smtp-relay dibelokkan ke IP lokal & koneksinya diam tanpa banner,
#      bikin send_mail menggantung sampai worker gunicorn mati). Port 443 lolos
#      normal, jadi ini jalur yang dipakai kalau kuncinya ada.
#   2. SMTP -- disimpan sebagai cadangan, buat hosting lain yang gak memblokir.
#   3. Console -- dev lokal tanpa kredensial apa pun.
if BREVO_API_KEY:
    EMAIL_BACKEND = "mark_up.email_backend.BrevoAPIEmailBackend"
elif os.getenv("EMAIL_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@markup.com")
# Inbox tim buat notifikasi internal yang butuh tindakan cepat (transaksi baru
# nunggu verifikasi, pesan masuk, pengajuan refund).
TEAM_NOTIFICATION_EMAIL = os.getenv("TEAM_NOTIFICATION_EMAIL", "markup.ofc@gmail.com")
PASSWORD_RESET_TIMEOUT = 60 * 30  # 30 menit, samain sama teks di halaman lupa password FE

FRONTEND_BASE_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Object storage S3-compatible (bisa Cloudflare R2, DomainEsia, atau provider
# S3-compatible lain -- generik, tinggal isi endpoint URL sesuai provider yang
# dipakai) buat media upload (bukti bayar, sertifikat, CV, foto profil).
# Sengaja fallback ke local filesystem storage kalau env var S3 belum lengkap
# diisi -- biar dev lokal & sebelum akun storage-nya aktif tetap jalan normal
# tanpa perlu ubah kode lagi pas kredensialnya udah ada, tinggal isi .env.
S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT_URL")
S3_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY_ID")
S3_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_ACCESS_KEY")
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
S3_REGION_NAME = os.getenv("S3_REGION_NAME", "auto")

USE_S3_STORAGE = all([S3_ENDPOINT_URL, S3_ACCESS_KEY_ID, S3_SECRET_ACCESS_KEY, S3_BUCKET_NAME])

# Fallback ke storage lokal cuma boleh di dev. Di produksi, satu env var S3
# yang kelupaan diisi bakal diam-diam nurunin SEMUA berkas user (bukti bayar,
# CV, dokumen pendaftaran, sertifikat) ke folder lokal -- dan folder itu dulu
# disajikan Nginx tanpa autentikasi. Gagal keras di sini jauh lebih baik
# daripada server nyala tapi dokumen pribadi user kebuka tanpa ada yang sadar.
if PRODUCTION and not USE_S3_STORAGE:
    from django.core.exceptions import ImproperlyConfigured

    _missing = [
        name
        for name, value in (
            ("S3_ENDPOINT_URL", S3_ENDPOINT_URL),
            ("S3_ACCESS_KEY_ID", S3_ACCESS_KEY_ID),
            ("S3_SECRET_ACCESS_KEY", S3_SECRET_ACCESS_KEY),
            ("S3_BUCKET_NAME", S3_BUCKET_NAME),
        )
        if not value
    ]
    raise ImproperlyConfigured(
        "PRODUCTION=True tapi object storage belum lengkap dikonfigurasi. "
        f"Env var yang masih kosong: {', '.join(_missing)}. "
        "Isi dulu di .env -- jangan jalanin produksi dengan storage lokal, "
        "berkas pribadi user bakal nyimpen di disk server tanpa proteksi."
    )

if USE_S3_STORAGE:
    # Botocore versi baru default-nya kirim checksum (x-amz-content-sha256)
    # yang belum semua provider S3-compatible non-AWS dukung dengan benar,
    # bikin error "XAmzContentSHA256Mismatch" pas upload. Ini fix standarnya --
    # balikin ke perilaku lama (checksum cuma kalau operasinya benar-benar
    # butuh, bukan selalu).
    os.environ.setdefault("AWS_REQUEST_CHECKSUM_CALCULATION", "when_required")
    os.environ.setdefault("AWS_RESPONSE_CHECKSUM_VALIDATION", "when_required")

    AWS_ACCESS_KEY_ID = S3_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = S3_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = S3_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = S3_ENDPOINT_URL
    AWS_S3_REGION_NAME = S3_REGION_NAME
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    # Bucket private (sesuai keputusan) -- Django generate presigned URL yang
    # kedaluwarsa, bukan link publik permanen.
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600  # 1 jam

    # Header yang nempel di objek waktu diunggah. "immutable" aman di sini
    # karena AWS_S3_FILE_OVERWRITE=False -- nama file selalu unik, jadi isi di
    # satu URL gak pernah berubah. Dipasangin sama memo URL di
    # mark_up/storage.py: header ini bikin browser MAU nyimpen, memo itu yang
    # bikin URL-nya konsisten sehingga simpanannya kepakai.
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "public, max-age=31536000, immutable"}

    STORAGES = {
        "default": {"BACKEND": "mark_up.storage.TolerantS3Storage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }