# Generated by Django 5.2.5 on 2026-06-21 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MENTORING', 'Mentoring'), ('MODULE', 'Module'), ('BOOTCAMP', 'Bootcamp'), ('EVENT_SPACE', 'Event Space')], default='MENTORING', max_length=20)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BootcampProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bootcamp_detail', serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Bootcamp Product',
                'verbose_name_plural': 'Bootcamp Products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EventSpaceProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_space_detail', serialize=False, to='products.product')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price_online', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_offline', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event Space Product',
                'verbose_name_plural': 'Event Space Products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MentoringProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mentoring_detail', serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Mentoring Product',
                'verbose_name_plural': 'Mentoring Products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='module_detail', serialize=False, to='products.product')),
                ('file_pdf_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Module Product',
                'verbose_name_plural': 'Module Products',
                'ordering': ['title'],
            },
        ),
    ]
