# Generated by Django 5.2.5 on 2026-06-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('MENTORING', 'Mentoring'), ('MODULE', 'Module'), ('BOOTCAMP', 'Bootcamp')], default='MENTORING', max_length=20),
        ),
        migrations.DeleteModel(
            name='EventSpaceProduct',
        ),
    ]
