# Generated by Django 5.2.5 on 2026-06-25 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_type_delete_eventspaceproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='mentor_profile',
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleproduct',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='moduleproduct',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bootcampproduct',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mentoringproduct',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='moduleproduct',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
