# Generated by Django 5.2.5 on 2026-07-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_review_mentor_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcampproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mentoringproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='moduleproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moduleproduct',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleproduct',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='moduleproduct',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='moduleproduct',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
