# Generated by Django 5.2.5 on 2026-07-14 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentorprofile_instagram_url'),
        ('products', '0005_remove_bootcampproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringproduct',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_products', to='mentors.mentorprofile'),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='session_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MentoringHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mentoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='products.mentoringproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
