# Generated by Django 6.0.4 on 2026-07-14 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentorprofile_instagram_url'),
        ('products', '0006_mentoringproduct_duration_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringproduct',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_products', to='mentors.mentorprofile'),
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_libraries', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_libraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Library',
                'verbose_name_plural': 'User Libraries',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_fee_percent', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='products.userlibrary')),
            ],
            options={
                'verbose_name': 'Refund Request',
                'verbose_name_plural': 'Refund Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('waiting_schedule', 'Waiting Schedule')], default='waiting_schedule', max_length=20)),
                ('zoom_link', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('availability_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_mentoring_sessions', to='mentors.mentoravailability')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mentoring_sessions', to='mentors.mentorprofile')),
                ('mentoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='products.mentoringproduct')),
                ('user_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='products.userlibrary')),
            ],
            options={
                'verbose_name': 'Mentoring Session',
                'verbose_name_plural': 'Mentoring Sessions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BootcampSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('waiting_schedule', 'Waiting Schedule')], default='waiting_schedule', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='products.bootcampproduct')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_sessions', to='mentors.mentorprofile')),
                ('user_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_sessions', to='products.userlibrary')),
            ],
            options={
                'verbose_name': 'Bootcamp Session',
                'verbose_name_plural': 'Bootcamp Sessions',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='userlibrary',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_library'),
        ),
    ]
