# Generated by Django 5.2.5 on 2026-07-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_mentoringproduct_mentor_userlibrary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringproduct',
            name='mentor',
        ),
    ]
