# Generated by Django 5.2.5 on 2026-07-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_mentoringproduct_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcampproduct',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mentoringproduct',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='moduleproduct',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
