# Generated by Django 5.2.16 on 2026-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_bootcampproduct_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
