# Generated by Django 5.2.16 on 2026-07-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
