# Generated by Django 5.2.16 on 2026-07-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_userlibrary_is_revoked'),
        ('programs', '0004_delete_mentoringsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampsession',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Sesi jadwal/template asal (dikelola admin) -- dipakai supaya update judul/mentor/link di template ikut ke-sync ke semua peserta yang sudah beli, karena satu sesi bootcamp itu kelas bareng dengan satu link yang sama untuk semua peserta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_sessions', to='programs.bootcampsession'),
        ),
    ]
