# Generated by Django 5.2.16 on 2026-07-22 15:21

from django.db import migrations
from django.db.models import Avg, Count


def backfill_mentor_rating(apps, schema_editor):
    MentorProfile = apps.get_model("mentors", "MentorProfile")
    MentoringSession = apps.get_model("products", "MentoringSession")
    BootcampSession = apps.get_model("products", "BootcampSession")
    Review = apps.get_model("products", "Review")

    for mentor in MentorProfile.objects.all():
        product_ids = set(
            MentoringSession.objects.filter(mentor_id=mentor.id).values_list(
                "mentoring__product_id", flat=True
            )
        ) | set(
            BootcampSession.objects.filter(mentor_id=mentor.id).values_list(
                "bootcamp__product_id", flat=True
            )
        )
        agg = Review.objects.filter(
            product_id__in=product_ids, is_hidden=False
        ).aggregate(avg=Avg("rating"), count=Count("id"))
        mentor.rating = round(agg["avg"] or 0, 2)
        mentor.review_count = agg["count"] or 0
        mentor.save(update_fields=["rating", "review_count"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_bootcampsession_template'),
        ('mentors', '0007_mentorprofile_bank_account_holder'),
    ]

    operations = [
        migrations.RunPython(backfill_mentor_rating, noop),
    ]
