# Generated by Django 5.2.16 on 2026-07-22 15:44

from django.db import migrations, models


def copy_mentor_to_mentors(apps, schema_editor):
    BootcampSession = apps.get_model("products", "BootcampSession")
    for session in BootcampSession.objects.exclude(mentor_id=None):
        session.mentors.add(session.mentor_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_mentorprofile_bank_account_holder'),
        ('products', '0014_backfill_mentor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampsession',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='bootcamp_sessions', to='mentors.mentorprofile'),
        ),
        migrations.RunPython(copy_mentor_to_mentors, noop),
        migrations.RemoveField(
            model_name='bootcampsession',
            name='mentor',
        ),
    ]
