# Generated by Django 5.2.16 on 2026-07-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_bootcampsession_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False, help_text="Ke-set True begitu admin buka halaman daftar ulasan -- dipakai buat badge notifikasi 'ulasan baru' di sidebar."),
        ),
    ]
