# Generated by Django 5.2.16 on 2026-07-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_mentorprofile_bank_account_holder'),
        ('products', '0016_review_is_seen_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringproduct',
            name='expertise',
            field=models.ManyToManyField(blank=True, help_text='Kategori mentoring (BCC, BPC, Karir, dst) -- nentuin mentor mana aja yang boleh dipilih pembeli produk ini (harus overlap sama keahlian mentor).', related_name='mentoring_products', to='mentors.expertise'),
        ),
    ]
