# Generated by Django 5.2.16 on 2026-07-24 03:19

from django.db import migrations

# Tebakan terbaik berdasarkan nama/deskripsi produk yang udah ada (BCC =
# Business Case Competition, BPC = Business Plan Competition) -- admin bisa
# koreksi lewat halaman Produk kalau ternyata salah kategori.
PRODUCT_EXPERTISE_MAP = {
    "101 Career Mentoring": ["Karir"],
    "Essential Sprint Registration": ["BCC"],
    "Full-Throttle Coaching": ["BCC"],
    "Bundling PowerPack (Newbie Friendly)": ["BCC"],
    "BPC Level-Up (Team Mentoring)": ["BPC"],
    "BPC Kickstart (Untuk Pemula, Individual Mentoring)": ["BPC"],
}


def seed_expertise(apps, schema_editor):
    Expertise = apps.get_model("mentors", "Expertise")
    MentoringProduct = apps.get_model("products", "MentoringProduct")

    names = {"BCC", "BPC", "Karir"}
    expertise_by_name = {}
    for name in names:
        obj, _ = Expertise.objects.get_or_create(name=name)
        expertise_by_name[name] = obj

    for title, expertise_names in PRODUCT_EXPERTISE_MAP.items():
        try:
            product = MentoringProduct.objects.get(title=title)
        except MentoringProduct.DoesNotExist:
            continue
        product.expertise.set([expertise_by_name[n] for n in expertise_names])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_mentoringproduct_expertise'),
    ]

    operations = [
        migrations.RunPython(seed_expertise, noop_reverse),
    ]
