# Generated by Django 5.2.16 on 2026-07-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_seed_expertise_and_tag_mentoring_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mentoringproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='moduleproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/'),
        ),
    ]
