# Generated by Django 5.2.16 on 2026-07-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_add_product_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampproduct',
            name='session_count',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah sesi kelas dalam batch ini. Pas produk dibuat/di-update naik, otomatis nge-generate slot sesi kosong (programs.BootcampSession) sejumlah ini, tinggal diisi tanggal/mentor/link-nya di Kelola Pesanan.'),
        ),
    ]
