# Generated by Django 5.2.16 on 2026-07-26 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_bootcampproduct_session_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('mentee', 'Mentee'), ('basic', 'Basic/Beginner'), ('premium', 'Premium/Intermediate'), ('elite', 'Elite/Advanced')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commitment_fee', models.DecimalField(decimal_places=2, default=0, help_text='Biaya komitmen yang dikembalikan di akhir program. Hanya paket Mentee yang punya (150k). Total bayar = price + commitment_fee.', max_digits=12)),
                ('requires_selection', models.BooleanField(default=False, help_text='True untuk Mentee: pendaftar wajib lolos seleksi (BCC test) dulu sebelum boleh bayar. Paket lain cukup di-ACC admin.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True)),
                ('benefit_session_material', models.BooleanField(default=True)),
                ('benefit_record_incubation', models.BooleanField(default=False)),
                ('benefit_framework_template', models.BooleanField(default=False)),
                ('benefit_winning_deck', models.BooleanField(default=False)),
                ('benefit_mentoring_case', models.BooleanField(default=False)),
                ('benefit_career_coaching', models.BooleanField(default=False)),
                ('benefit_team_pairing', models.BooleanField(default=False)),
                ('benefit_networking', models.BooleanField(default=False)),
                ('benefit_ecertificate', models.BooleanField(default=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='products.bootcampproduct')),
            ],
            options={
                'verbose_name': 'Bootcamp Package',
                'verbose_name_plural': 'Bootcamp Packages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BootcampRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_doc', models.FileField(help_text='Satu PDF gabungan berisi 5 bukti syarat pendaftaran.', upload_to='bootcamp_registrations/%Y/%m/')),
                ('status', models.CharField(choices=[('registered', 'Menunggu Ditinjau'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='registered', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='products.bootcamppackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bootcamp Registration',
                'verbose_name_plural': 'Bootcamp Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bootcamppackage',
            constraint=models.UniqueConstraint(fields=('bootcamp', 'slug'), name='unique_bootcamp_package_slug'),
        ),
        migrations.AddConstraint(
            model_name='bootcampregistration',
            constraint=models.UniqueConstraint(fields=('user', 'package'), name='unique_user_bootcamp_package_registration'),
        ),
    ]
