# Generated by Django 5.2.16 on 2026-07-26 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_seed_bootcamp_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampTimelineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Kosongkan kalau cuma satu hari (mis. hari pengumuman).', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='products.bootcampproduct')),
            ],
            options={
                'verbose_name': 'Bootcamp Timeline Item',
                'verbose_name_plural': 'Bootcamp Timeline Items',
                'ordering': ['order', 'start_date'],
            },
        ),
    ]
