# Generated by Django 5.2.16 on 2026-07-26 07:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_seed_bootcamp_timeline_and_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamppackage',
            name='quiz_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Durasi tes BCC (menit) -- cuma relevan buat paket dengan requires_selection=True.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='bootcamppackage',
            name='quiz_passing_score_percent',
            field=models.PositiveIntegerField(default=70, help_text='Ambang nilai lulus (%) tes BCC -- dipakai buat auto-flag lulus/tidak, keputusan akhir Terima/Tolak tetap manual oleh admin.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='BootcampQuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_order', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(help_text='started_at + package.quiz_duration_minutes, dihitung sekali saat attempt dibuat. Ini yang dipakai server buat cek expired, BUKAN countdown di client -- countdown di browser cuma tampilan.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Sedang Dikerjakan'), ('submitted', 'Selesai Dikumpulkan'), ('expired', 'Waktu Habis (Auto-submit)')], default='in_progress', max_length=20)),
                ('score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempt', to='products.bootcampregistration')),
            ],
            options={
                'verbose_name': 'Bootcamp Quiz Attempt',
                'verbose_name_plural': 'Bootcamp Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BootcampQuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('choice_a', models.CharField(max_length=255)),
                ('choice_b', models.CharField(max_length=255)),
                ('choice_c', models.CharField(max_length=255)),
                ('choice_d', models.CharField(max_length=255)),
                ('correct_choice', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='products.bootcampproduct')),
            ],
            options={
                'verbose_name': 'Bootcamp Quiz Question',
                'verbose_name_plural': 'Bootcamp Quiz Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BootcampQuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_choice', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.bootcampquizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='products.bootcampquizquestion')),
            ],
            options={
                'verbose_name': 'Bootcamp Quiz Answer',
                'verbose_name_plural': 'Bootcamp Quiz Answers',
                'ordering': ['answered_at'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_answer')],
            },
        ),
    ]
