# Generated by Django 5.2.16 on 2026-07-26 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_bootcamppackage_quiz_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_libraries', to='products.bootcamppackage'),
        ),
        migrations.CreateModel(
            name='BootcampResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('record_incubation', 'Record Incubation'), ('framework_template', 'Framework Template'), ('winning_deck', 'Winning Deck')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='bootcamp_resources/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='products.bootcampproduct')),
            ],
            options={
                'verbose_name': 'Bootcamp Resource',
                'verbose_name_plural': 'Bootcamp Resources',
                'ordering': ['resource_type', '-created_at'],
            },
        ),
    ]
