# Generated by Django 5.2.16 on 2026-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_userlibrary_package_bootcampresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamppackage',
            name='min_attendance_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Minimal jumlah sesi bootcamp berstatus selesai (per peserta) buat berhak dapat pengembalian commitment fee. 0 = gak ada syarat kehadiran. Cuma relevan buat paket yang punya commitment_fee > 0.'),
        ),
    ]
