# Generated by Django 5.2.16 on 2026-07-26 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_bootcamppackage_min_attendance_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamppackage',
            name='payment_deadline_at',
            field=models.DateTimeField(blank=True, help_text='Batas waktu bayar buat pendaftar yang sudah Diterima (mis. jendela bayar Mentee di timeline). Kosong = gak ada batas waktu otomatis -- admin urus manual. Kalau lewat, tombol bayar terkunci sampai admin ubah keputusan/tenggat.', null=True),
        ),
        migrations.CreateModel(
            name='BootcampTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='products.bootcampproduct')),
            ],
            options={
                'verbose_name': 'Bootcamp Team',
                'verbose_name_plural': 'Bootcamp Teams',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BootcampTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='products.bootcampteam')),
                ('user_library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to='products.userlibrary')),
            ],
            options={
                'verbose_name': 'Bootcamp Team Member',
                'verbose_name_plural': 'Bootcamp Team Members',
                'ordering': ['joined_at'],
            },
        ),
    ]
