# Generated by Django 5.2.16 on 2026-07-27 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_bootcamppackage_payment_deadline_at_bootcampteam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='products.bootcampproduct')),
            ],
            options={
                'verbose_name': 'Bootcamp Requirement',
                'verbose_name_plural': 'Bootcamp Requirements',
                'ordering': ['order'],
            },
        ),
    ]
