# Generated by Django 5.2.16 on 2026-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_seed_bootcamp_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootcamprequirement',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Bootcamp Requirement', 'verbose_name_plural': 'Bootcamp Requirements'},
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='commitment_letter_max_words',
            field=models.PositiveIntegerField(default=500, help_text='Batas maksimal kata buat commitment/motivation letter pendaftar, ditampilkan sebagai informasi di halaman pendaftaran publik.'),
        ),
        migrations.AddField(
            model_name='bootcampregistration',
            name='commitment_letter',
            field=models.FileField(blank=True, help_text='Commitment/motivation letter terpisah dari PDF syarat -- strukturnya diatur admin. Nullable karena ini requirement baru, pendaftaran lama (kalau ada) gak punya file ini; wajib diisi buat pendaftaran BARU (dicek di view, bukan di sini).', null=True, upload_to='bootcamp_commitment_letters/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='bootcamprequirement',
            name='category',
            field=models.CharField(choices=[('general', 'Syarat Umum'), ('commitment_letter', 'Struktur Commitment Letter')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='bootcampregistration',
            name='requirement_doc',
            field=models.FileField(help_text='Satu PDF gabungan berisi bukti syarat pendaftaran (jumlah & isi diatur admin).', upload_to='bootcamp_registrations/%Y/%m/'),
        ),
    ]
