# Generated by Django 5.2.16 on 2026-07-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_seed_commitment_letter_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamppackage',
            name='selection_quota',
            field=models.PositiveIntegerField(blank=True, help_text="Target jumlah pendaftar yang mau diterima lewat seleksi paket ini. Kosong = gak ada batas. Ini CUMA indikator progres di panel admin ('12/30 diterima') -- gak pernah ngunci tombol Terima, sama kayak pola 'eligible' di fitur lain (skor tes, refund commitment fee): keputusan Terima/Tolak tetap manual sepenuhnya di tangan admin.", null=True),
        ),
        migrations.AlterField(
            model_name='bootcamppackage',
            name='requires_selection',
            field=models.BooleanField(default=False, help_text="Kalau True: pendaftar wajib lolos seleksi (tes BCC) dulu sebelum boleh bayar. Kalau False: cukup di-ACC admin. Dinamis per paket, gak terikat ke paket 'Mentee' secara khusus -- admin bisa nyalain/matiin dari panel Kelola Pesanan Bootcamp."),
        ),
    ]
