# Generated by Django 5.2.16 on 2026-07-28 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_bootcamppackage_selection_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamppackage',
            name='slug',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='BootcampPackageExtraBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_benefits', to='products.bootcamppackage')),
            ],
            options={
                'verbose_name': 'Bootcamp Package Extra Benefit',
                'verbose_name_plural': 'Bootcamp Package Extra Benefits',
                'ordering': ['order', 'id'],
            },
        ),
    ]
