# Generated by Django 5.2.16 on 2026-07-28 15:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_bootcamppackage_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcampquizattempt',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='products.bootcampregistration'),
        ),
        migrations.AlterField(
            model_name='bootcampquizquestion',
            name='bootcamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='products.bootcampproduct'),
        ),
        migrations.CreateModel(
            name='BootcampQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Tes Seleksi BCC', max_length=150)),
                ('duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('passing_score_percent', models.PositiveIntegerField(default=70, help_text='Ambang lulus (%) buat auto-flag. Keputusan akhir Terima/Tolak tetap manual di tangan admin.', validators=[django.core.validators.MaxValueValidator(100)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Kalau dimatiin, tes gak muncul ke peserta. Attempt yang sudah terlanjur dikerjakan tetap tersimpan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='products.bootcampproduct')),
                ('timeline_item', models.ForeignKey(blank=True, help_text='Opsional -- tes ini bagian dari milestone timeline yang mana. SET_NULL biar hapus milestone gak ikut ngapus tes & jawabannya.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='products.bootcamptimelineitem')),
            ],
            options={
                'verbose_name': 'Bootcamp Quiz',
                'verbose_name_plural': 'Bootcamp Quizzes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='bootcampquizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='products.bootcampquiz'),
        ),
        migrations.AddField(
            model_name='bootcampquizquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='products.bootcampquiz'),
        ),
        migrations.AddConstraint(
            model_name='bootcampquizattempt',
            constraint=models.UniqueConstraint(fields=('registration', 'quiz'), name='unique_attempt_per_registration_quiz'),
        ),
    ]
