# Generated by Django 5.2.16 on 2026-07-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_backfill_bootcamp_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcampquizquestion',
            name='bootcamp',
        ),
    ]
