# Generated by Django 5.2.16 on 2026-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_bootcampquizquestion_bootcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampregistration',
            name='cv',
            field=models.FileField(blank=True, help_text='CV pendaftar. Pindah ke sini dari profil user -- dulu diunggah sekali di profil, sekarang diminta per pendaftaran biar selalu versi terbaru. Nullable di DB demi pendaftaran lama; wajib buat pendaftaran BARU (dicek di view).', null=True, upload_to='bootcamp_cv/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='bootcampregistration',
            name='portfolio',
            field=models.FileField(blank=True, help_text='Portofolio pendaftar -- OPSIONAL, beneran boleh kosong (beda dari cv/commitment_letter yang nullable cuma demi data lama).', null=True, upload_to='bootcamp_portfolio/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='bootcampregistration',
            name='commitment_letter',
            field=models.FileField(blank=True, help_text='Commitment/motivation letter, diunggah sebagai SATU file PDF. Strukturnya diatur admin. Nullable karena ini requirement baru, pendaftaran lama (kalau ada) gak punya file ini; wajib diisi buat pendaftaran BARU (dicek di view, bukan di sini).', null=True, upload_to='bootcamp_commitment_letters/%Y/%m/'),
        ),
    ]
