# Generated by Django 5.2.16 on 2026-08-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_bootcampregistration_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoPopupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Saklar utama. Kalau dimatiin, popup gak tampil sama sekali walau tanggalnya masih berlaku.')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Kosong = langsung tayang begitu diaktifkan.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Kosong = tayang terus sampai dimatiin manual.', null=True)),
                ('headline', models.CharField(blank=True, default='', help_text='Judul di popup. Kosong = pakai judul produknya.', max_length=150)),
                ('cta_label', models.CharField(blank=True, default='Daftar Sekarang', help_text='Tulisan di tombol.', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Produk yang dipromosikan. SET_NULL biar hapus produk gak ikut ngapus setelan popup-nya.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_popups', to='products.product')),
            ],
            options={
                'verbose_name': 'Promo Popup Setting',
                'verbose_name_plural': 'Promo Popup Settings',
            },
        ),
    ]
