# Generated by Django 5.2.16 on 2026-08-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_promopopupsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampresource',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='Paket mana yang boleh mengunduh. KOSONG = semua peserta bootcamp ini (tetap harus sudah bayar -- bukan publik).', related_name='resources', to='products.bootcamppackage'),
        ),
        migrations.AlterField(
            model_name='bootcampresource',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('record_incubation', 'Record Incubation'), ('framework_template', 'Framework Template'), ('winning_deck', 'Winning Deck')], default='', help_text='Sekarang cuma label kategori. Hak aksesnya ditentukan `packages`.', max_length=30),
        ),
    ]
