# Generated by Django 5.2.16 on 2026-08-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_bootcampresource_packages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampresource',
            name='for_all_packages',
            field=models.BooleanField(default=True, help_text='True = semua peserta bootcamp ini boleh mengunduh (tetap harus sudah bayar -- bukan publik). False = cuma paket di `packages`.'),
        ),
        migrations.AlterField(
            model_name='bootcampresource',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='Dipakai cuma kalau for_all_packages=False.', related_name='resources', to='products.bootcamppackage'),
        ),
    ]
