# Generated by Django 6.0.7 on 2026-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_bootcamp_group_and_referral_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_gateway_mode',
            field=models.CharField(choices=[('AUTO', 'Otomatis (ikut pengaturan iPaymu)'), ('MANUAL_ONLY', 'Selalu Transfer Manual')], default='AUTO', help_text='Metode bayar buat produk ini -- lihat catatan di PaymentGatewayMode soal urutan penentuan bareng saklar master IpaymuSetting.is_enabled.', max_length=20),
        ),
    ]
