# Generated by Django 6.0.7 on 2026-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_product_payment_gateway_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampproduct',
            name='community_link',
            field=models.URLField(blank=True, default='', help_text='Link grup WhatsApp komunitas peserta. Ditampilkan begitu peserta submit pembayaran (belum perlu nunggu ACC admin) dan di halaman detail bootcamp mereka di Produk Saya. Kosongkan kalau belum ada grupnya -- ajakannya otomatis gak ditampilkan.'),
        ),
        migrations.AddField(
            model_name='bootcampproduct',
            name='owned_description',
            field=models.TextField(blank=True, default='', help_text='Deskripsi yang ditampilkan ke peserta yang SUDAH BELI, di halaman detail bootcamp mereka -- BEDA dari `description` di atas yang tampil di /produk (katalog publik). Kosongkan buat pakai deskripsi publik yang sama seperti sekarang.'),
        ),
    ]
