# Generated by Django 6.0.7 on 2026-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_bootcampproduct_community_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampproduct',
            name='community_message',
            field=models.TextField(blank=True, default='', help_text='Teks ajakan yang ditampilkan berdampingan dengan tombol gabung grup WhatsApp (di kartu setelah submit pembayaran, dan di halaman Produk Saya). Kosongkan buat pakai teks bawaan.'),
        ),
    ]
