from django.urls import path

from .views import (
    add_product,
    get_my_products,
    get_my_product_detail,
    rate_my_product,
    refund_my_product,
    schedule_my_product_session,
    get_products,
    product_detail_view,
    get_product_summary,
    get_refund_requests,
    update_refund_request,
    get_certificates,
    issue_certificate,
    get_my_certificates,
    get_mentoring_orders,
    get_mentoring_order_detail,
    update_mentoring_order_session,
    get_bootcamp_orders,
    get_bootcamp_order_detail,
    update_bootcamp_order_session,
    get_all_reviews,
    toggle_review_visibility,
    upload_product_image,
    get_bootcamp_packages,
    register_bootcamp,
    get_my_bootcamp_registrations,
    get_bootcamp_registrations,
    review_bootcamp_registration,
    get_bootcamp_timeline,
    add_bootcamp_timeline_item,
    update_bootcamp_timeline_item,
    update_bootcamp_package,
    add_bootcamp_package,
    delete_bootcamp_package,
    add_package_extra_benefit,
    delete_package_extra_benefit,
    get_promo_popup,
    admin_promo_popup,
    get_zoom_accounts,
    add_zoom_account,
    zoom_account_detail,
    test_zoom_account,
    get_bootcamp_quizzes,
    add_bootcamp_quiz,
    update_bootcamp_quiz,
    get_bootcamp_quiz_questions,
    add_bootcamp_quiz_question,
    update_bootcamp_quiz_question,
    start_or_resume_bootcamp_quiz,
    save_bootcamp_quiz_answer,
    submit_bootcamp_quiz,
    create_bootcamp_payment,
    get_bootcamp_resources,
    add_bootcamp_resource,
    update_bootcamp_resource,
    get_bootcamp_teams,
    add_bootcamp_team,
    update_bootcamp_team,
    assign_bootcamp_team_member,
    remove_bootcamp_team_member,
    randomize_bootcamp_teams,
    get_bootcamp_requirements,
    add_bootcamp_requirement,
    update_bootcamp_requirement,
    update_commitment_letter_settings,
)

urlpatterns = [
    path("", get_products, name="api_products_list"),
    path("promo-popup/", get_promo_popup, name="api_promo_popup"),
    path("promo-popup/admin/", admin_promo_popup, name="api_promo_popup_admin"),
    path("zoom-accounts/", get_zoom_accounts, name="api_zoom_accounts"),
    path("zoom-accounts/add/", add_zoom_account, name="api_zoom_account_add"),
    path("zoom-accounts/<uuid:account_id>/", zoom_account_detail, name="api_zoom_account_detail"),
    path("zoom-accounts/<uuid:account_id>/test/", test_zoom_account, name="api_zoom_account_test"),
    path("refund-requests/", get_refund_requests, name="api_refund_requests_list"),
    path("refund-requests/<uuid:refund_id>/", update_refund_request, name="api_refund_request_update"),
    path("certificates/", get_certificates, name="api_certificates_list"),
    path("certificates/add/", issue_certificate, name="api_certificates_issue"),
    path("certificates/me/", get_my_certificates, name="api_my_certificates"),
    path("mentoring-orders/", get_mentoring_orders, name="api_mentoring_orders_list"),
    path("mentoring-orders/<uuid:user_library_id>/", get_mentoring_order_detail, name="api_mentoring_order_detail"),
    path("mentoring-orders/sessions/<uuid:session_id>/", update_mentoring_order_session, name="api_mentoring_order_session_update"),
    path("bootcamp-orders/", get_bootcamp_orders, name="api_bootcamp_orders_list"),
    path("bootcamp-orders/<uuid:user_library_id>/", get_bootcamp_order_detail, name="api_bootcamp_order_detail"),
    path("bootcamp-orders/sessions/<uuid:session_id>/", update_bootcamp_order_session, name="api_bootcamp_order_session_update"),
    path("reviews/", get_all_reviews, name="api_reviews_list"),
    path("reviews/<uuid:review_id>/toggle/", toggle_review_visibility, name="api_review_toggle"),
    path("bootcamp-register/", register_bootcamp, name="api_bootcamp_register"),
    path("bootcamp-registrations/", get_bootcamp_registrations, name="api_bootcamp_registrations_list"),
    path("bootcamp-registrations/me/", get_my_bootcamp_registrations, name="api_my_bootcamp_registrations"),
    path("bootcamp-registrations/<uuid:registration_id>/review/", review_bootcamp_registration, name="api_bootcamp_registration_review"),
    path("bootcamp-packages/<uuid:package_id>/", update_bootcamp_package, name="api_bootcamp_package_update"),
    path("bootcamp-packages/<uuid:package_id>/delete/", delete_bootcamp_package, name="api_bootcamp_package_delete"),
    path("bootcamp-packages/<uuid:package_id>/extra-benefits/add/", add_package_extra_benefit, name="api_bootcamp_package_extra_benefit_add"),
    path("bootcamp-extra-benefits/<uuid:benefit_id>/", delete_package_extra_benefit, name="api_bootcamp_package_extra_benefit_delete"),
    path("bootcamp-timeline/<uuid:item_id>/", update_bootcamp_timeline_item, name="api_bootcamp_timeline_item_update"),
    path("bootcamp-requirements/<uuid:item_id>/", update_bootcamp_requirement, name="api_bootcamp_requirement_update"),
    path("bootcamp-quizzes/<uuid:quiz_id>/", update_bootcamp_quiz, name="api_bootcamp_quiz_update"),
    path("bootcamp-quizzes/<uuid:quiz_id>/questions/", get_bootcamp_quiz_questions, name="api_bootcamp_quiz_questions"),
    path("bootcamp-quizzes/<uuid:quiz_id>/questions/add/", add_bootcamp_quiz_question, name="api_bootcamp_quiz_question_add"),
    path("bootcamp-quiz-questions/<uuid:question_id>/", update_bootcamp_quiz_question, name="api_bootcamp_quiz_question_update"),
    path("bootcamp-registrations/<uuid:registration_id>/quizzes/<uuid:quiz_id>/start/", start_or_resume_bootcamp_quiz, name="api_bootcamp_quiz_start"),
    path("bootcamp-quiz-attempts/<uuid:attempt_id>/answer/", save_bootcamp_quiz_answer, name="api_bootcamp_quiz_answer"),
    path("bootcamp-quiz-attempts/<uuid:attempt_id>/submit/", submit_bootcamp_quiz, name="api_bootcamp_quiz_submit"),
    path("bootcamp-registrations/<uuid:registration_id>/pay/", create_bootcamp_payment, name="api_bootcamp_registration_pay"),
    path("bootcamp-resources/<uuid:resource_id>/", update_bootcamp_resource, name="api_bootcamp_resource_update"),
    path("bootcamp-teams/<uuid:team_id>/", update_bootcamp_team, name="api_bootcamp_team_update"),
    path("bootcamp-teams/<uuid:team_id>/members/", assign_bootcamp_team_member, name="api_bootcamp_team_member_assign"),
    path("bootcamp-team-members/<uuid:member_id>/", remove_bootcamp_team_member, name="api_bootcamp_team_member_remove"),
    path("summary/", get_product_summary, name="api_products_summary"),
    path("add/", add_product, name="api_products_add"),
    path("upload-image/", upload_product_image, name="api_products_upload_image"),
    path("my-products/", get_my_products, name="api_my_products_list"),
    path("my-products/<uuid:product_id>/", get_my_product_detail, name="api_my_product_detail"),
    path("my-products/<uuid:product_id>/rate/", rate_my_product, name="api_my_product_rate"),
    path("my-products/<uuid:product_id>/refund/", refund_my_product, name="api_my_product_refund"),
    path("my-products/sessions/<uuid:session_id>/schedule/", schedule_my_product_session, name="api_my_product_schedule"),
    path("<uuid:product_id>/packages/", get_bootcamp_packages, name="api_bootcamp_packages"),
    path("<uuid:product_id>/packages/add/", add_bootcamp_package, name="api_bootcamp_package_add"),
    path("<uuid:product_id>/timeline/", get_bootcamp_timeline, name="api_bootcamp_timeline"),
    path("<uuid:product_id>/timeline/add/", add_bootcamp_timeline_item, name="api_bootcamp_timeline_add"),
    path("<uuid:product_id>/requirements/", get_bootcamp_requirements, name="api_bootcamp_requirements"),
    path("<uuid:product_id>/requirements/add/", add_bootcamp_requirement, name="api_bootcamp_requirement_add"),
    path("<uuid:product_id>/commitment-letter-settings/", update_commitment_letter_settings, name="api_bootcamp_commitment_letter_settings"),
    path("<uuid:product_id>/quizzes/", get_bootcamp_quizzes, name="api_bootcamp_quizzes"),
    path("<uuid:product_id>/quizzes/add/", add_bootcamp_quiz, name="api_bootcamp_quiz_add"),
    path("<uuid:product_id>/resources/", get_bootcamp_resources, name="api_bootcamp_resources"),
    path("<uuid:product_id>/resources/add/", add_bootcamp_resource, name="api_bootcamp_resource_add"),
    path("<uuid:product_id>/teams/", get_bootcamp_teams, name="api_bootcamp_teams"),
    path("<uuid:product_id>/teams/add/", add_bootcamp_team, name="api_bootcamp_team_add"),
    path("<uuid:product_id>/teams/randomize/", randomize_bootcamp_teams, name="api_bootcamp_teams_randomize"),
    path("<uuid:product_id>/", product_detail_view, name="api_product_detail"),
]
