from django.urls import path

from .views import (
    add_product,
    get_my_products,
    get_my_product_detail,
    rate_my_product,
    refund_my_product,
    schedule_my_product_session,
    get_products,
    product_detail_view,
    get_product_summary,
    get_refund_requests,
    update_refund_request,
    get_certificates,
    issue_certificate,
    get_my_certificates,
    get_mentoring_orders,
    get_mentoring_order_detail,
    update_mentoring_order_session,
    get_bootcamp_orders,
    get_bootcamp_order_detail,
    update_bootcamp_order_session,
    get_all_reviews,
    toggle_review_visibility,
)

urlpatterns = [
    path("", get_products, name="api_products_list"),
    path("refund-requests/", get_refund_requests, name="api_refund_requests_list"),
    path("refund-requests/<uuid:refund_id>/", update_refund_request, name="api_refund_request_update"),
    path("certificates/", get_certificates, name="api_certificates_list"),
    path("certificates/add/", issue_certificate, name="api_certificates_issue"),
    path("certificates/me/", get_my_certificates, name="api_my_certificates"),
    path("mentoring-orders/", get_mentoring_orders, name="api_mentoring_orders_list"),
    path("mentoring-orders/<uuid:user_library_id>/", get_mentoring_order_detail, name="api_mentoring_order_detail"),
    path("mentoring-orders/sessions/<uuid:session_id>/", update_mentoring_order_session, name="api_mentoring_order_session_update"),
    path("bootcamp-orders/", get_bootcamp_orders, name="api_bootcamp_orders_list"),
    path("bootcamp-orders/<uuid:user_library_id>/", get_bootcamp_order_detail, name="api_bootcamp_order_detail"),
    path("bootcamp-orders/sessions/<uuid:session_id>/", update_bootcamp_order_session, name="api_bootcamp_order_session_update"),
    path("reviews/", get_all_reviews, name="api_reviews_list"),
    path("reviews/<uuid:review_id>/toggle/", toggle_review_visibility, name="api_review_toggle"),
    path("summary/", get_product_summary, name="api_products_summary"),
    path("add/", add_product, name="api_products_add"),
    path("my-products/", get_my_products, name="api_my_products_list"),
    path("my-products/<uuid:product_id>/", get_my_product_detail, name="api_my_product_detail"),
    path("my-products/<uuid:product_id>/rate/", rate_my_product, name="api_my_product_rate"),
    path("my-products/<uuid:product_id>/refund/", refund_my_product, name="api_my_product_refund"),
    path("my-products/sessions/<uuid:session_id>/schedule/", schedule_my_product_session, name="api_my_product_schedule"),
    path("<uuid:product_id>/", product_detail_view, name="api_product_detail"),
]
