# Generated by Django 5.2.5 on 2026-07-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentoringsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
