# Generated by Django 5.2.5 on 2026-07-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentorprofile_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
