# Generated by Django 5.2.5 on 2026-07-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentorprofile_headline_mentorprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
