# Generated by Django 5.2.16 on 2026-07-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_mentorprofile_review_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentoringSession',
        ),
    ]
