# Generated by Django 5.2.16 on 2026-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_delete_mentoringsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='bank_account_holder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
