# Generated by Django 5.2.16 on 2026-07-24 16:21

from django.db import migrations, models


def dedupe_availability(apps, schema_editor):
    """Bersihin slot availability yang kedouble (mentor+start_time sama) SEBELUM
    unique constraint dipasang. Pertahankan slot yang udah dibooking (kalau ada),
    kalau sama-sama belum kebooking pertahankan yang paling awal dibuat; sisanya
    dihapus. Sesi mentoring yang udah nunjuk ke slot pakai on_delete=SET_NULL,
    jadi aman -- referensi ke slot yang kehapus otomatis jadi null."""
    MentorAvailability = apps.get_model("mentors", "MentorAvailability")
    from collections import defaultdict

    groups = defaultdict(list)
    for slot in MentorAvailability.objects.all().order_by("id"):
        groups[(slot.mentor_profile_id, slot.start_time)].append(slot)

    for slots in groups.values():
        if len(slots) < 2:
            continue
        # Prioritas dipertahankan: yang is_booked=True duluan, lalu urutan id.
        slots.sort(key=lambda s: (not s.is_booked,))
        keep = slots[0]
        for extra in slots:
            if extra.id != keep.id:
                extra.delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_mentorprofile_bank_account_holder'),
    ]

    operations = [
        migrations.RunPython(dedupe_availability, noop_reverse),
        migrations.AddConstraint(
            model_name='mentoravailability',
            constraint=models.UniqueConstraint(fields=('mentor_profile', 'start_time'), name='unique_mentor_availability_slot'),
        ),
    ]
