# Generated by Django 5.2.16 on 2026-07-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0010_lock_expertise_to_3_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='mentoring_fee_percent_override',
            field=models.PositiveIntegerField(blank=True, help_text='Persentase komisi mentoring khusus mentor ini (0-100). Kosong = pakai persentase global dari CommissionSetting.', null=True),
        ),
    ]
