# Generated by Django 5.2.5 on 2026-06-21 08:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(help_text='Human-readable transaction code', max_length=30, primary_key=True, serialize=False)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('QRIS', 'QRIS'), ('E_WALLET', 'E-Wallet'), ('CREDIT_CARD', 'Credit Card'), ('MANUAL', 'Manual')], default='BANK_TRANSFER', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_at_checkout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='products.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Item',
                'verbose_name_plural': 'Transaction Items',
                'ordering': ['transaction', 'product'],
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_libraries', to='products.product')),
                ('transaction_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_access', to='transactions.transactionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Library',
                'verbose_name_plural': 'User Libraries',
                'ordering': ['-active_date'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='transaction_user_id_b60ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_status'], name='transaction_payment_9e5bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['transaction'], name='transaction_transac_0cdaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['product'], name='transaction_product_266d98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionitem',
            unique_together={('transaction', 'product')},
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['user'], name='transaction_user_id_478087_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['product'], name='transaction_product_27a0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['active_date'], name='transaction_active__8aec62_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['expire_date'], name='transaction_expire__cc1492_idx'),
        ),
        migrations.AddConstraint(
            model_name='userlibrary',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'transaction_item'), name='unique_user_product_transaction_item'),
        ),
    ]
