# Generated by Django 5.2.5 on 2026-06-25 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
        ('products', '0004_remove_review_mentor_profile_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userlibrary',
            name='unique_user_product_transaction_item',
        ),
        migrations.RemoveIndex(
            model_name='userlibrary',
            name='transaction_product_27a0ef_idx',
        ),
        migrations.AlterUniqueTogether(
            name='transactionitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='product',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='mentor_availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_item', to='mentors.mentoravailability'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.UniqueConstraint(fields=('transaction', 'product', 'mentor_availability'), name='unique_transaction_product_availability'),
        ),
        migrations.AddConstraint(
            model_name='userlibrary',
            constraint=models.UniqueConstraint(fields=('user', 'transaction_item'), name='unique_user_product_transaction_item'),
        ),
    ]
