# Generated by Django 5.2.5 on 2026-07-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_userlibrary_unique_user_product_transaction_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='proof_of_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
