# Generated by Django 5.2.5 on 2026-07-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_buyer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='proof_of_payment_url',
        ),
        migrations.AddField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/'),
        ),
    ]
