# Generated by Django 5.2.5 on 2026-07-16 05:56

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_proof_of_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=transactions.models.generate_transaction_id, editable=False, help_text='Human-readable transaction code', max_length=30, primary_key=True, serialize=False),
        ),
    ]
