# Generated by Django 5.2.16 on 2026-07-17 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_mentorprofile_bank_account_holder'),
        ('products', '0011_certificate'),
        ('transactions', '0006_delete_userlibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('mentoring', 'Mentoring'), ('bootcamp', 'Bootcamp')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_percent', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='products.bootcampsession')),
                ('mentor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='mentors.mentorprofile')),
                ('mentoring_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='products.mentoringsession')),
            ],
            options={
                'verbose_name': 'Mentor Payout',
                'verbose_name_plural': 'Mentor Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quota', models.PositiveIntegerField()),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='referral_codes', to='products.product')),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCodeUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='transactions.referralcode')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_usage', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code Usage',
                'verbose_name_plural': 'Referral Code Usages',
                'ordering': ['-created_at'],
            },
        ),
    ]
