# Generated by Django 5.2.16 on 2026-07-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_mentorprofile_bank_account_holder'),
        ('products', '0015_remove_bootcampsession_mentor_and_more'),
        ('transactions', '0007_mentorpayout_referralcode_referralcodeusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorpayout',
            name='bootcamp_session',
            field=models.ForeignKey(blank=True, help_text='ForeignKey (bukan OneToOne) karena satu sesi bootcamp bisa diajar >1 mentor -- tiap mentor yang ditugaskan dapat baris payout sendiri-sendiri untuk sesi yang sama.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='products.bootcampsession'),
        ),
        migrations.AddConstraint(
            model_name='mentorpayout',
            constraint=models.UniqueConstraint(condition=models.Q(('bootcamp_session__isnull', False)), fields=('bootcamp_session', 'mentor_profile'), name='unique_bootcamp_session_mentor_payout'),
        ),
    ]
