# Generated by Django 5.2.16 on 2026-07-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_mentorpayout_bootcamp_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Catatan dari pembeli, misal nama-nama anggota tim buat pesanan grup.'),
        ),
    ]
