# Generated by Django 5.2.16 on 2026-07-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commitment_letter',
            field=models.FileField(blank=True, help_text='Commitment letter (foto atau PDF).', null=True, upload_to='bootcamp_docs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='follow_proof',
            field=models.FileField(blank=True, help_text='Bukti follow (foto).', null=True, upload_to='bootcamp_docs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wa_share_proof',
            field=models.FileField(blank=True, help_text='Bukti share WhatsApp (foto).', null=True, upload_to='bootcamp_docs/%Y/%m/'),
        ),
    ]
