# Generated by Django 5.2.16 on 2026-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_bootcamp_checkout_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentoring_fee_percent', models.PositiveIntegerField(default=25)),
            ],
            options={
                'verbose_name': 'Commission Setting',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
    ]
