# Generated by Django 5.2.16 on 2026-07-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_bootcamppackage_quiz_duration_minutes_and_more'),
        ('transactions', '0011_commission_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bootcamp_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='products.bootcampregistration'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commitment_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
