# Generated by Django 5.2.16 on 2026-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_transaction_bootcamp_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commitment_fee_refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
