# Generated by Django 5.2.16 on 2026-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_commitment_fee_refunded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Mandiri', max_length=100)),
                ('account_number', models.CharField(default='', max_length=50)),
                ('account_holder', models.CharField(default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Account Setting',
                'verbose_name_plural': 'Bank Account Settings',
            },
        ),
    ]
