# Generated by Django 6.0.7 on 2026-09-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_alter_ipaymusetting_default_expired_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ipaymu_qr_string',
            field=models.TextField(blank=True, default='', help_text='Payload teks QRIS (format EMVCo standar) dari QRIS Direct Payment -- disimpan biar pembeli yang reload/kembali ke halaman bayar lihat QR yang SAMA (bukan bikin sesi baru tiap reload), selama masih dalam jendela expires_at. Digambar ulang jadi QR code di frontend, BUKAN gambar/URL dari iPaymu -- lihat catatan di mark_up/ipaymu.py.'),
        ),
    ]
