# Generated by Django 6.0.7 on 2026-09-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_transaction_ipaymu_qr_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='team_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
